/*
 * Copyright (c) 2024-2030 星曳数据
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * This file is provided under the Mozilla Public License Version 2.0,
 * and the "NO WARRANTY" clause of the MPL is hereby expressly
 * acknowledged.
 */
namespace Air.Cloud.Core.Standard.SchedulerStandard.Coordination
{
    /// <summary>
    /// <para>zh-cn:调度执行上下文，描述一次触发在分布式环境中的唯一性维度。</para>
    /// <para>en-us:Scheduler execution context that describes uniqueness dimensions for one distributed fire.</para>
    /// </summary>
    public sealed class SchedulerExecutionContext
    {
        /// <summary>
        /// <para>zh-cn:服务名称，用于隔离不同应用或微服务。</para>
        /// <para>en-us:Service name used to isolate applications or microservices.</para>
        /// </summary>
        public string ServiceName { get; set; } = string.Empty;

        /// <summary>
        /// <para>zh-cn:任务唯一标识。</para>
        /// <para>en-us:Unique job identifier.</para>
        /// </summary>
        public string JobId { get; set; } = string.Empty;

        /// <summary>
        /// <para>zh-cn:任务分组名称。</para>
        /// <para>en-us:Job group name.</para>
        /// </summary>
        public string GroupName { get; set; } = string.Empty;

        /// <summary>
        /// <para>zh-cn:任务名称。</para>
        /// <para>en-us:Job name.</para>
        /// </summary>
        public string JobName { get; set; } = string.Empty;

        /// <summary>
        /// <para>zh-cn:Quartz 计划触发时间，按 UTC 保存。</para>
        /// <para>en-us:Quartz scheduled fire time stored as UTC.</para>
        /// </summary>
        public DateTimeOffset? ScheduledFireTimeUtc { get; set; }

        /// <summary>
        /// <para>zh-cn:调度框架本次触发实例标识。</para>
        /// <para>en-us:Scheduler framework fire instance identifier.</para>
        /// </summary>
        public string FireInstanceId { get; set; } = string.Empty;

        /// <summary>
        /// <para>zh-cn:当前服务实例标识。</para>
        /// <para>en-us:Current service instance identifier.</para>
        /// </summary>
        public string OwnerId { get; set; } = string.Empty;

        /// <summary>
        /// <para>zh-cn:执行唯一键；为空时由协调器按唯一模式生成。</para>
        /// <para>en-us:Execution unique key; generated by the coordinator when empty.</para>
        /// </summary>
        public string ExecutionKey { get; set; } = string.Empty;

        /// <summary>
        /// <para>zh-cn:执行租约时长。</para>
        /// <para>en-us:Execution lease duration.</para>
        /// </summary>
        public TimeSpan LeaseTime { get; set; } = TimeSpan.FromMinutes(5);

        /// <summary>
        /// <para>zh-cn:唯一执行策略。</para>
        /// <para>en-us:Unique execution policy.</para>
        /// </summary>
        public SchedulerExecutionUniqueMode UniqueMode { get; set; } = SchedulerExecutionUniqueMode.PerFireTime;

        /// <summary>
        /// <para>zh-cn:执行记录实体类型；为空时由协调器自动扫描唯一实现。</para>
        /// <para>en-us:Execution record entity type; when empty, the coordinator scans the single implementation automatically.</para>
        /// </summary>
        public Type? ExecutionRecordType { get; set; }
    }
}
